### ISSUE TITLE
sorguda hata

### ISSUE THREAD

**Issue by GabrielSSQ** [fastuptime/Instagram_People_Near_Me#1]
module.exports = { sorgu }; kodunda for (let i = 0; i < response.native_location_data.ranked.sections.length; i++) {
                                                      ^

TypeError: Cannot read properties of undefined (reading 'ranked')
 hatası veriyor

**Comment by fastuptime** [comment]
response.native_location_data?.ranked.sections.length; i++) {

**Comment by GabrielSSQ** [comment]
bu kezde tamamıyla 0 kişi buluyor.

**Comment by fastuptime** [comment]
Nereyi sorguluyorsunuz ki ve hesap açık olmadan instagram a girebiliyor musunuz?

**Comment by GabrielSSQ** [comment]
215765815 sorguladığım yer...

**Comment by fastuptime** [comment]
hesap açık olmadan instagram a girebiliyor musunuz?
sorgu.js ayarlarını girdiniz mi

**Comment by GabrielSSQ** [comment]
ayarları görmemiştim, hallettim teşekkürler
